gyms/urls.py
from django.urls import path

from . import views

app_name = 'gyms'
urlpatterns = [
    path('', views.index, name='index'),
    path('gym/<int:gym_id>', views.gym_detail, name='gym_detail'),
    path('trainer/<int:trainer_id>', views.trainer_detail, name='trainer_detail'),
    path('add_abonement/', views.add_abonement, name='add_abonement'),
    path('delete_abonement/', views.delete_abonement, name='delete_abonement'),
    path('register/', views.register, name='register'),
    path('personal_account/<int:user_id>', views.information_of_user, name='information_of_user'),
    path('edit_profile/<int:user_id>', views.edit_profile, name='edit_profile'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('gyms/', include('gyms.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

gyms/models.py
from django.db import models
from django.contrib.auth.models import User


class Gym(models.Model):
    name = models.CharField(max_length=200)
    time_work = models.CharField(max_length=100)
    adress = models.CharField(max_length=200)


    def __str__(self):
        return self.name


class Trainer(models.Model):
    name = models.CharField(max_length=200)
    year_old = models.IntegerField(default=0)
    time_work = models.CharField(max_length=100)
    gym = models.ForeignKey(Gym, on_delete=models.CASCADE, null=True, related_name='trainers')


    def __str__(self):
        return self.name


class Abonement(models.Model):
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE,
                                related_name='abonements')
    gym = models.ForeignKey(Gym, on_delete=models.CASCADE,
                                related_name='abonements')
    profile = models.ForeignKey('Profile', on_delete=models.CASCADE,
                                related_name='abonements')
    time = models.CharField(max_length=100, default='-')

    def __str__(self):
        return f'{self.id} - {self.profile} - {self.trainer} - {self.gym} - {self.time}'





class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

gyms/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Profile


User = get_user_model()

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ("username", "first_name", 'last_name', "email")

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", 'last_name', "email", "password1", "password2",)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user

gyms/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpRequest
from .models import Gym, Trainer, Abonement
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib import messages
from .forms import UserForm, NewUserForm




def index(request):
    return render(request, 'gyms/index.html', {'title': 'Тренажерки', 'gyms': Gym.objects.all()})


def gym_detail(request, gym_id: int):
    info = Abonement.objects.filter(profile=request.user.profile, gym__id=gym_id)
    if info:
        cheack_element = False
    else:
        cheack_element = True
    return render(request, 'gyms/gym_detail.html', {
        'gym': get_object_or_404(Gym, id=gym_id), 'cheack_element': cheack_element
    })

def trainer_detail(request, trainer_id: int):
    return render(request, 'gyms/trainer_detail.html', {
        'trainer': get_object_or_404(Trainer, id=trainer_id),
    })

@login_required
def add_abonement(request: HttpRequest):
    gym = get_object_or_404(Gym, id=request.POST['gym_id'])
    trainer = get_object_or_404(Trainer, id=request.POST['trainer_id'])
    profile = request.user.profile
    abonement = Abonement.objects.create(gym=gym, trainer=trainer, profile=profile, time=request.POST['time'])
    return redirect('gyms:gym_detail', request.POST['gym_id'])

def delete_abonement(request):
    gym = get_object_or_404(Gym, id=request.POST['gym_id'])
    abonement = Abonement.objects.filter(gym=gym, profile=request.user.profile)
    abonement.delete()
    request.user.profile.save()
    return redirect('gyms:gym_detail', request.POST['gym_id'])

def register(request):
    if request.method == 'POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Вы зарегестрировались успешно.")
            return redirect('gyms:index')
        else:
            messages.error(request, "Нормально регайся!")
            return render(request, "registration/register.html", context={"form": form})


@login_required
def information_of_user(request, user_id):
    user = get_object_or_404(User, id=user_id)
    abonement = Abonement.objects.filter(profile=request.user.profile)
    return render(request, 'gyms/personal_account.html', {'user': user, 'abonement':abonement})


@login_required
def edit_profile(request, user_id):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            user = get_object_or_404(User, id=user_id)
            user.username = username
            user.email = email
            user.first_name = first_name
            user.last_name = last_name
            user.save()
            return redirect('gyms:personal_account', user.id)
    else:
        form = UserForm(instance=request.user)
    return render(request, 'gyms/edit_profile.html', {'form': form})

gyms/templates/gyms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{% block tittle %} Тренажерки {% endblock %}</title>
</head>
<body>
    <a href="{% url 'gyms:index' %}">Главная страница</a>
    {% if user.is_authenticated %}
        <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-danger"/>
        </form>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
    {% endif %}
        {% if user.is_authenticated %}
            <li class="nav-item px-1">
                <a href="{% url 'gyms:information_of_user' user.id %}" class="btn btn-primary">{{ user.username }}</a>
            </li>
        {% endif %}
    {% block body %}{% endblock %}
</body>
</html>

gyms/templates/gyms/edit_profile.html
{% extends 'gyms/base.html' %}

{% block body %}
    <br/><h3>Редактировать информацию профиля:</h3>
    <form action="{% url 'gyms:edit_profile' user.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Apply">
    </form>
{% endblock %}

gyms/templates/gyms/gym_detail.html
{% extends 'gyms/base.html' %}


{% block body %}
    <h1>{{ gym.name }}</h1>
    <p>время работы - {{ gym.time_work }}   ({{ gym.adress }})</p>
    <ul>
        <h4>Тренера в зале:</h4>
        <ul>
            {% for trainer in gym.trainers.all %}
                <li><a href="{% url 'gyms:trainer_detail' trainer.id %}">{{ trainer.name }}</a></li>
                <h8>{{ trainer.year_old }} лет</h8>
                <p>время работы - {{ trainer.time_work }}</p>
            {% endfor %}
        </ul>
        {% if user.is_authenticated %}
            {% if cheack_element %}
            <h1>Забронировать абонемент</h1>
            <h3>Тренеры:</h3>
            <form action="{% url 'gyms:add_abonement' %}" method="post">
                {% csrf_token %}
            {% for trainer in gym.trainers.all %}
                <input type="radio" name="trainer_id" value="{{ trainer.id }}"
                    id="trainer_id-{{ forloop.counter }}"/>
                <label for="trainer_id-{{ forloop.counter }}">
                    {{ trainer.name }}
                </label><br>
            {% endfor %}
                <h3>Время:</h3>
                <input type="text" name="time" placeholder="Напишите время">
                <input type="submit" value="Добавить абонемент" class="btn btn-info"/>
                <input type="hidden" name="gym_id" value="{{ gym.id }}">
                {% else %}
                    <h3>У вас уже имеется абонемент на этот зал</h3>
                    <form action="{% url 'gyms:delete_abonement' %}" method="post">
                        {%csrf_token%}
                    <input type='submit' value='Удалить абонемент'>
                    <input type='hidden' name='gym_id' value="{{ gym.id }}">
                    </form>
                {% endif %}
        {% endif %}
        </ul>
{% endblock %}

gyms/templates/gyms/index.html
{% extends 'gyms/base.html' %}

{% block body %}
{% if not gyms %}
    <h1>There are no gyms</h1>
{% else %}
    <h1>Какой тренажерный зал по вкусу?</h1>
    <ul>
        {% for gym in gyms %}
            <li>
                <a href="{% url 'gyms:gym_detail' gym.id %}">{{ gym.name }}</a>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"> время работы - {{ gym.time_work }}   ({{ gym.adress }})</a></li>
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

gyms/templates/gyms/personal_account.html
{% extends 'gyms/base.html' %}

{% block body %}
        <h1 style="text-align:left;font-family:verdana;color:Purple">Личный кабинет пользователя</h1>
    <div class="row">
        <div class="col-sm-4" style="background-color:active;"><h4 style="font-family:verdana;color:Green";>Имя пользователя:{{user.username}}</h4>
        <div class="col-sm-3" style="background-color:active;"><h5 style="font-family:verdana;color:Blue";>Email:{{user.email}}</h5></div>
        <div class="col-sm-3" style="background-color:active;"><h5 style="font-family:verdana;color:Blue">Имя:{{user.first_name}}</h5></div>
        <div class="col-sm-2" style="background-color:active;"><h5 style="font-family:verdana;color:Blue">Фамилия:{{user.last_name}}</h5></div>
            <h1><a href="{% url 'gyms:edit_profile' user.id %}" class="btn btn-primary">Редактировать профиль</a></h1>
     </div>
    <ul>
            <h1>Абонементы:</h1>
        {% for info in abonement %}
            <h3>{{ info.profile.user.username }}</h3>
            <li>
                <p>{{ info.trainer.name }}</p>
            </li>
            <p>{{ info.time }}</p>
            <p>{{ info.gym }}</p>
        {% endfor %}
    </ul>
{% endblock %}

gyms/templates/gyms/trainer_detail.html
{% extends 'gyms/base.html' %}

{% block body %}
    <h1>{{ trainer.name }}</h1>
    <h>{{ trainer.year_old }} лет</h>
    <p>время работы - {{ trainer.time_work }}</p>
    <ul>
        <li>Место работы: Тренажерный зал
            <a href="{% url 'gyms:gym_detail' trainer.gym.id %}">
            "{{ trainer.gym.name }}"
            </a>
        </li>
    </ul>
{% endblock %}